### PR TITLE
Added replanning if it deviates more than 0.3 meters

### PR DESCRIPTION
**Pull request by vbalaji21**
2 changes -
1) Replanning if it deviates more than 0.3 meters from the next waypoint
2) made elseif to else for (self.goal != self.current) as timestamp was involved in triggering replanning and the robot was spinning when it reached the goal sometimes

### CODE REVIEW

**Comment by franklinselva** [comment]
@vbalaji21 Were we able to verify the replanning?

Also, what happens when we are trying to increase more than 3 humans in the simulator.

**Comment by vbalaji21** [comment]
@franklinselva It works well for 4 humans in morse but for 10 humans. The simulator becomes slow.

**Comment by franklinselva** [comment]
> @franklinselva It works well for 4 humans in morse but for 10 humans. The simulator becomes slow.

Running each of these humans in parallel processes may help distribute the effort.

**Comment by vbalaji21** [comment]
@franklinselva you mean like threads and mutex, my machine is a single core machine so a software parallelism is an option.

**Pull request merged**
